version=1.11.0-SNAPSHOT
group=org.jetbrains.kotlinx

# First-party dependencies.
# ONLY rename these properties alongside adapting kotlinx.train build chain
# and the `firstPartyDependencies` list in `buildSrc`.
kotlin_version=2.3.21
atomicfu_version=0.32.1

# Dependencies
benchmarks_version=0.5.0
benchmarks_jmh_version=1.37
junit_version=4.12
junit5_version=5.7.0
knit_version=0.5.0
lincheck_version=2.18.1
dokka_version=2.2.0-Beta
byte_buddy_version=1.17.6
reactor_version=3.4.1
reactor_docs_version=3.4.5
reactive_streams_version=1.0.3
rxjava2_version=2.2.8
rxjava3_version=3.0.2
javafx_version=17.0.2
javafx_plugin_version=0.1.0
kover_version=0.9.8
blockhound_version=1.0.8.RELEASE
jna_version=5.9.0

# Gradle
jdk_toolchain_version=11
animalsniffer_version=2.0.1

# Android versions
android_version=4.1.1.4
androidx_annotation_version=1.1.0
robolectric_version=4.9
baksmali_version=2.2.7

# Settings

org.gradle.jvmargs=-Xmx3g

kotlinx.atomicfu.enableJvmIrTransformation=true

org.gradle.caching=true
# Enabling configuration cache speeds up local builds during development.
org.gradle.configuration-cache=true
# Inconviniently, enabling configuration cache also enables build and execution parallelism by default.
# Many targets will be built and tests executed at the same time with high parallelism.
# Many tests are memory-bound and timing-sensitive (e.g. real timeouts), so parallel build and execution
# leads to CPU and memory starvation and manifests as flaky tests and OOMs on CI.
# Setting org.gradle.workers.max to 1 will revert to sequential build and execution as before enabling CC,
# yet it seems like the CI can handle 2 workers, so we will keep it for now.
#
# Revert to 1 worker if flaky tests and OOMs are observed again on CI.
#
# Feel free to comment out this workers restriction for your local build during development
# to speed up local build and tests, and see if your local machine can manage it.
org.gradle.workers.max=2
