kotlin_version=2.4.20-dev-8851
kotlin.native.version=2.4.20-dev-8851
kotlin_repo_url=https://packages.jetbrains.team/maven/p/kt/dev

kotlin_language_version=2.4
kotlin_api_version=2.4
kotlin_Werror_override=disable

build_snapshot_train=true
skip_snapshot_checks=true
kotlin.internal.compiler.arguments.log.level=warning
