kotlin_version=2.4.255-SNAPSHOT
kotlin.native.version=2.4.255-SNAPSHOT
kotlin_repo_url=file:///Users/Nikolay.Lunyak/Documents/Projects/kotlin-worktrees/kotlin-platform-type-commonized-to-different-types/build/repo

kotlin_language_version=2.4
kotlin_api_version=2.4
kotlin_Werror_override=disable

build_snapshot_train=true
skip_snapshot_checks=true
kotlin.internal.compiler.arguments.log.level=warning
